name: NPM Publish@latest

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com/@thencc'
          always-auth: true
          # creates an .npmrc

      # - name: "install"
      #   run: npm ci

      # - name: "build"
      #   run: npm run build

      # really, re-tags a certain push as @latest, doesnt publish again
      - name: "publish"
        # run: npm publish --access public # old
        run: |
          npm config set registry https://registry.npmjs.org/
          PKG_VERSION_LOCAL=`cat package.json | jq -r '.version'`
          npm dist-tag add @thencc/inkey-types@$PKG_VERSION_LOCAL latest
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}